// <auto-generated>
//   GENERATED BY tools/selection_present_check.py - DO NOT EDIT.
//
//   Everything below the marker is lifted VERBATIM out of
//   src/Quill/Controls/InkSurface.cs.  The point of the harness this belongs to
//   is that it runs the REAL fade against the REAL serialiser; a hand-copied
//   Veil would only prove that a copy is pure.  Regenerate with:
//
//       python tools/selection_present_check.py
// </auto-generated>
using Quill.Helpers;
using Windows.UI;

namespace Quill.Tools;

/// <summary>InkSurface's fade, out of its control and into a console.</summary>
public sealed class RealVeil
{
    // ---- harness surface (the only hand-written code in this file) --------
    // InkSurface drives _veil from a CompositionTarget.Rendering tick and reads
    // ExportChromeless off a property the export window sets.  Neither exists
    // here, so the two inputs are exposed and everything between them is the
    // real thing.
    public void Drive(double veil, bool exportChromeless)
    {
        _veil = veil;
        ExportChromeless = exportChromeless;
    }

    public double Level => _veil;
    public bool IsVeiling => Veiling;
    public Color Apply(Color c, bool exempt) => Veil(c, exempt);
    public bool ExportChromeless { get; set; }

    // ======================= VERBATIM FROM InkSurface.cs ===================
    private static readonly Color VeilGrey = Color.FromArgb(0xFF, 0x8E, 0x8E, 0x8E);


    private double _veil;          // 0 = the page's own colours, 1 = fully #8E8E8E

    private bool Veiling => _veil > 0.0005 && !ExportChromeless;

    private Color Veil(Color c, bool exempt = false)
    {
        if (exempt || !Veiling) return c;
        double t = Motion.FadeEase(_veil);
        static byte Mix(byte a, byte b, double k) => (byte)Math.Clamp(a + (b - a) * k, 0, 255);
        return Color.FromArgb(c.A, Mix(c.R, VeilGrey.R, t), Mix(c.G, VeilGrey.G, t), Mix(c.B, VeilGrey.B, t));
    }
}
