#!/usr/bin/env python3
"""Write gen_undo.py's literal into Icons.cs, preserving the file's CRLF.

Icons.cs is CRLF and ToolWheel.cs is LF; this repo mixes them per file, so
the endings are read off the target rather than assumed.  The replacement
spans from the `public const string UndoRound =` line to the semicolon that
ends the declaration, comment block included.
"""
from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_undo as G                                            # noqa: E402

ICONS = os.path.join(os.path.dirname(HERE), "src", "Quill", "Helpers", "Icons.cs")

DOC = '''    /// <summary>Undo, redesigned - reference 11.2 item 14, head re-authored
    /// for 16.6.
    ///
    /// <para>The mark above is a straight arrow that hooks round a loop, which
    /// at the 18 DIP the dial's centre buttons run at reads as a knot. This one
    /// is what an undo control actually is: a three-quarter ROTATION. A 284
    /// degree band of mid radius 8.15 and half-width 0.56 about (12, 12.3),
    /// swept from -52 to 232 degrees, with an open chevron head where it stops.
    /// Redo is this mirrored, exactly as before, so the pair still cannot drift
    /// apart.</para></summary>
    public const string UndoRound =
        // FILLED OUTLINE, not a stroke: the top bar draws these through
        // PathIcon, which fills its Data and cannot stroke, so one geometry has
        // to serve both PathIcon and Icons.Mark.
        //
        // The outline is FLATTENED to line segments. Caps built from `A`
        // commands bulge inward when the sweep flag is wrong and yield bowtie
        // geometry - that shipped once as a blob. Sampling the offset curve
        // removes the class of bug: no flags remain to get backwards.
        //
        // 16.6, "the arrow tip is longer on the outer side". The head was a
        // textbook isoceles chevron - both arms 4.9 long, both swept back 54
        // degrees - and still lopsided, because the shaft is an ARC. A chevron
        // pinned at the arc's END throws its outer tip further out than its
        // inner tip goes in, by exactly
        //
        //     r_out + r_in - 2R  =  1.233 units  =  1.08 px at SatSize 21
        //
        // which is the complaint, measured. Equalising it by bending the arms
        // to different angles (the obvious fix) reads WORSE - the eye reads a
        // chevron by its arm angles first - so the head stays a perfect mirror
        // about the shaft and is instead SLID ALONG THE RADIUS until the two
        // tips are equidistant from the ring: vertex radius 7.580 rather than
        // 8.150. Arms come down 4.9 -> 4.4 and the sweep 54 -> 52 degrees, the
        // smallest change that leaves the head legible at 21 DIP. Measured on
        // a 64x raster of the finished fill, caps and joins included:
        //
        //     ink reaches 3.227 past the outer edge, 3.226 inside the inner
        //     one - 0.001 units, a thousandth of a pixel at 21 DIP.
        //
        // F1 IS LOAD-BEARING. The head is one closed outline and the band is
        // another, wound the same way, so NONZERO unions them. The default
        // fill rule is even-odd, under which the old head's two overlapping arm
        // capsules XOR'd a white notch out of their own vertex.
        //
        // WRAPPING MATTERS HERE. This literal is split across lines, and a break
        // that lands between a coordinate's x and y - with no space carried
        // across the join - fuses them into a number that cannot parse, and the
        // whole mark silently renders BLANK. That shipped too. Breaks are now
        // only ever between whole commands, and each chunk keeps its trailing
        // space. scratchpad/verify_icons.py reassembles every literal and
        // re-parses it; run it after ANY edit here.
        //
        // Generated by scratchpad/gen_undo.py; regenerate rather than hand-edit.
'''


def main():
    raw = open(ICONS, "rb").read()
    crlf = raw.count(b"\r\n")
    text = raw.decode("utf-8").replace("\r\n", "\n")

    m = re.search(r"^    /// <summary>Undo, redesigned.*?^    public const string UndoRound =.*?;\n",
                  text, re.S | re.M)
    if not m:
        raise SystemExit("UndoRound block not found")

    block = DOC + G.literal() + "\n"
    text = text[:m.start()] + block + text[m.end():]

    out = text.replace("\n", "\r\n") if crlf else text
    open(ICONS, "wb").write(out.encode("utf-8"))
    print(f"Icons.cs rewritten ({'CRLF' if crlf else 'LF'} preserved), "
          f"{len(block.splitlines())} lines in the new block")


if __name__ == "__main__":
    main()
